---

- name: Creating kafka Mirror Maker configurations | properties files
  template:
    src: "{{ item }}"
    dest: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}/config/{{ item }}"
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
    mode: 0775
  loop:
    - kafka-mirror-maker-consumer.properties
    - kafka-mirror-maker-producer.properties

- name: Creating kafka Mirror Maker configurations | properties files
  template:
    src: "tools-log4j.properties"
    dest: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}/config/kafka-mirror-log4j-{{ item }}.properties"
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
    mode: 0775
  loop: "{{ range(1, kafkaMirrorMakerProcessCountPerNode + 1, 1) | list }}"

- name: Creating kafka Mirror Maker configurations | kafka-mirror-maker.sh
  template:
    src: kafka-mirror-maker.sh
    dest: "{{ kafkaInstallDir }}/kafka_{{ kafkaScalaVersion }}-{{ kafkaVersion }}/bin/kafka-mirror-maker-{{ item }}.sh"
    owner: "{{ kafkaUser }}"
    group: "{{ kafkaGroup }}"
    mode: 0775
  loop: "{{ range(1, kafkaMirrorMakerProcessCountPerNode + 1, 1) | list }}"