---

- name: OS Tunning
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { "key":"vm.max_map_count", "value": "{{ kafkaVmMaxMapCount }}" }
  ignore_errors: true

- name: Networking Tunning
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: true
  loop:
    - { "key": "net.ipv4.tcp_max_syn_backlog", "value": "40000" }
    - { "key": "net.core.somaxconn", "value": "40000" }
    - { "key": "net.ipv4.tcp_sack", "value": "1" }
    - { "key": "net.ipv4.tcp_window_scaling", "value": "1" }
    - { "key": "net.ipv4.tcp_fin_timeout", "value": "15" }
    - { "key": "net.ipv4.tcp_keepalive_intvl", "value": "60" }
    - { "key": "net.ipv4.tcp_keepalive_probes", "value": "5" }
    - { "key": "net.ipv4.tcp_keepalive_time", "value": "180" }
    - { "key": "net.ipv4.tcp_tw_reuse", "value": "1" }
    - { "key": "net.ipv4.tcp_moderate_rcvbuf", "value": "1" }
    - { "key": "net.core.rmem_default", "value": "8388608" }
    - { "key": "net.core.wmem_default", "value": "8388608" }
    - { "key": "net.core.rmem_max", "value": "134217728" }
    - { "key": "net.core.wmem_max", "value": "134217728" }
    - { "key": "net.ipv4.tcp_mem", "value": "134217728 134217728 134217728" }
    - { "key": "net.ipv4.tcp_rmem", "value": "4096 277750 134217728" }
    - { "key": "net.ipv4.tcp_wmem", "value": "4096 277750 134217728" }
    - { "key": "net.core.netdev_max_backlog", "value": "300000" }
  ignore_errors: true